"""
data_ingestion.py — Task 1: Project Setup + Data Ingestion (ETL)
Capstone Project - I | Bluestock Mutual Fund Analytics

Covers:
 - Loading all 10 CSV datasets and printing shape, dtypes, head()
 - Documenting anomalies / quality summary
 - AMFI code validation (every fund_master code present in nav_history)
 - Explore fund_master: unique fund houses, categories, sub-categories, risk grades

All paths are resolved via config.py — nothing is hardcoded.
"""

import sys
import json
import logging
import warnings

import pandas as pd
from pathlib import Path

warnings.filterwarnings("ignore")

# ─── Import config ────────────────────────────────────────────────────────────
sys.path.insert(0, str(Path(__file__).resolve().parent))
import config as C

# ─── Logger ───────────────────────────────────────────────────────────────────
logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
log = logging.getLogger(__name__)

# ─── Ensure output directories exist ─────────────────────────────────────────
for d in [C.DIRS["processed"], C.DIRS["reports"]]:
    d.mkdir(parents=True, exist_ok=True)


# ─── 1. Inspect all datasets ──────────────────────────────────────────────────
def inspect_datasets() -> dict:
    """Load all CSV files from data/raw/, print shape, dtypes, and head().

    Returns
    -------
    dict
        Mapping of filename → DataFrame for all successfully loaded CSVs.
    """
    csv_files = sorted(C.DIRS["raw"].glob("*.csv"))

    if not csv_files:
        log.error("No CSV files found in '%s'. Check your data folder.", C.DIRS["raw"])
        return {}

    log.info("Found %d datasets. Beginning ingestion and inspection...", len(csv_files))
    datasets: dict = {}

    for fp in csv_files:
        log.info("=" * 55)
        log.info("DATASET: %s", fp.name)
        log.info("=" * 55)

        try:
            df = pd.read_csv(fp)
            datasets[fp.name] = df
            log.info("  SHAPE : %s", df.shape)
            log.info("  DTYPES:\n%s", df.dtypes.to_string())
            log.info("  HEAD  :\n%s", df.head().to_string())
        except Exception as exc:
            log.error("  Failed to load %s: %s", fp.name, exc)

    return datasets


# ─── 2. Validate AMFI codes ───────────────────────────────────────────────────
def validate_amfi_codes() -> bool:
    """Confirm every AMFI code in fund_master exists in nav_history.

    Returns
    -------
    bool
        True if all codes are present, False otherwise.
    """
    fund_master  = pd.read_csv(C.DIRS["raw"] / C.RAW_FILES["fund_master"])
    nav_history  = pd.read_csv(C.DIRS["raw"] / C.RAW_FILES["nav_history"])

    master_codes = set(fund_master["amfi_code"].astype(str))
    nav_codes    = set(nav_history["amfi_code"].astype(str))
    missing      = master_codes - nav_codes

    if missing:
        log.warning("AMFI codes in fund_master but NOT in nav_history: %s", missing)
        return False

    log.info("AMFI Code Validation PASSED — all %d codes present in nav_history.", len(master_codes))
    return True


# ─── 3. Explore fund_master ───────────────────────────────────────────────────
def explore_fund_master() -> None:
    """Print unique fund houses, categories, sub-categories, and risk grades."""
    df = pd.read_csv(C.DIRS["raw"] / C.RAW_FILES["fund_master"])

    for col in ["fund_house", "category", "sub_category", "risk_category"]:
        if col in df.columns:
            vals = df[col].dropna().unique()
            log.info("Unique %s (%d): %s", col, len(vals), sorted(vals))


# ─── 4. Generate quality report ───────────────────────────────────────────────
def generate_quality_report() -> Path:
    """Scan all raw CSVs for missing values, duplicates, and range violations.

    Saves findings to reports/data_quality_summary.md.

    Returns
    -------
    Path
        Path to the generated Markdown report.
    """
    lines = ["# Data Quality Summary\n", f"Generated by data_ingestion.py\n\n"]

    for key, fname in C.RAW_FILES.items():
        fp = C.DIRS["raw"] / fname
        if not fp.exists():
            lines.append(f"## {fname}\n⚠️ File not found.\n\n")
            continue

        df = pd.read_csv(fp)
        missing  = df.isnull().sum()
        dups     = df.duplicated().sum()
        total_mv = int(missing.sum())

        lines.append(f"## {fname}\n")
        lines.append(f"- Shape: {df.shape[0]} rows × {df.shape[1]} columns\n")
        lines.append(f"- Duplicate rows: {dups}\n")
        lines.append(f"- Total missing values: {total_mv}\n")

        if total_mv > 0:
            mv_cols = missing[missing > 0]
            lines.append("- Missing per column:\n")
            for col, cnt in mv_cols.items():
                pct = cnt / len(df) * 100
                lines.append(f"  - {col}: {cnt} ({pct:.1f}%)\n")
        lines.append("\n")

    out = C.DIRS["reports"] / "data_quality_summary.md"
    out.write_text("".join(lines), encoding="utf-8")
    log.info("Quality report saved: %s", out)
    return out


# ─── Main ─────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    inspect_datasets()
    validate_amfi_codes()
    explore_fund_master()
    generate_quality_report()
